### ISSUE TITLE
Feature: Develop the navigation bar

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#1]
## Description
Develop the navigation bar as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8?node-id=4-598).

## Tasks
- [ ] Develop the navigation as per the Figma designs
- [ ] Make sure the components are fully responsive
- [ ] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![1730287377162](https://github.com/user-attachments/assets/d7b418e0-9405-4ea5-9191-0d6bcc6e97d9)

**Comment by giahungb2111886** [comment]
I would like to work on issue. Assign it to me pls...
