### ISSUE TITLE
Feature: Develop the landing page navbar

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#12]
## Description
Develop the landing page navigation bar as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=12443-1656&node-type=frame&t=JcKZg5Vn24zgOIdM-0). Include sign up and login pages.
 

## Tasks
- [ ] Develop the navigation as per the Figma designs
- [ ] Make sure the components are fully responsive
- [ ] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality
- [ ] Include a list of any API endpoints required in the pull request description, if applicable

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![CoLab Landing Navbar](https://github.com/user-attachments/assets/f550d687-21c2-4a9c-a06c-ec7e531b5b18)
![CoLabs Sign Up](https://github.com/user-attachments/assets/9f19ef28-0704-42f6-a01a-dde1ee4c6d3d)
![CoLabs Log In](https://github.com/user-attachments/assets/cb139d1a-21df-4faa-b015-a0a25b5e7450)
