### ISSUE TITLE
Feature: Develop the hero section

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#13]
## Description
Develop the hero section as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=12443-1656&node-type=frame&t=JcKZg5Vn24zgOIdM-0).
 

## Tasks
- [ ] Develop the hero section as per the Figma designs
- [ ] Make sure the components are fully responsive
- [ ] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality
- [ ] Include a list of any API endpoints required in the pull request description, if applicable

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![CoLabs Hero](https://github.com/user-attachments/assets/309c19dd-812d-4191-9a1a-f33fc2bb7db2)

**Comment by patricksolka** [comment]
Hey @bridgitkanini would love to work on this!

**Comment by samoina** [comment]
did you work on this @patricksolka ?
