### ISSUE TITLE
Feature: Develop the leaderboard section

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#14]
## Description
Develop the leaderboard section as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=12443-1656&node-type=frame&t=JcKZg5Vn24zgOIdM-0).
 

## Tasks
- [ ] Develop the leaderboard section as per the Figma designs
- [ ] Make sure the components are fully responsive
- [ ] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality
- [ ] Include a list of any API endpoints required in the pull request description, if applicable

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![CoLabs Leaderboard](https://github.com/user-attachments/assets/dcbf2753-126d-4b4e-b1a3-9a3ba9244b67)
