### ISSUE TITLE
Feature: Develop the tools section

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#15]
## Description
Develop the tools section as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=12443-1656&node-type=frame&t=JcKZg5Vn24zgOIdM-0).
 

## Tasks
- [x] Develop the tools section as per the Figma designs
- [x] Make sure the components are fully responsive
- [x] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality
- [x] Include a list of any API endpoints required in the pull request description, if applicable

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![CoLabs Gamification](https://github.com/user-attachments/assets/8a5b1d78-7923-45a9-a2fc-6461bc53d9cf)
