### ISSUE TITLE
Feature: Develop repositories section

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#16]
## Description
Develop the repositories section on the landing page as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=12443-1656&node-type=frame&t=JcKZg5Vn24zgOIdM-0).
 

## Tasks
- [x] Develop the repositories section on the landing page per the Figma designs
- [x] Make sure the components are fully responsive
- [x] Write _e2e_ tests to test the components' look, feel, and functionality 

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![CoLabs Repos](https://github.com/user-attachments/assets/da72c684-99bd-40dc-b39c-744f8cb6baba)
