### ISSUE TITLE
Feature: Develop CTA & footer

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#18]
## Description
Develop  Call To Action(CTA) section and  footer  as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=12443-1656&node-type=frame&t=JcKZg5Vn24zgOIdM-0).
 

## Tasks
- [ ] Develop the  Call To Action section and footer per the Figma designs
- [ ] Make sure the components are fully responsive
- [ ] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality
- [ ] Include a list of any API endpoints required in the pull request description, if applicable

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![CoLabs CTA   Footer](https://github.com/user-attachments/assets/91522b70-a282-40e4-b4ea-e781f4ceb77d)
