### ISSUE TITLE
Feature: Develop dashboard navbar

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#19]
## Description
Develop the dashboard navigation bar as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=11544-8713&node-type=frame&t=QP5ajT4tDzJ46YUn-0). Include [add a project page](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=12568-10476&node-type=frame&t=JcKZg5Vn24zgOIdM-0)
 

## Tasks
- [x] Develop the navigation as per the Figma designs
- [x] Make sure the components are fully responsive
- [x] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality
- [x] Include a list of any API endpoints required in the pull request description, if applicable

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![CoLab Dashboard Navbar](https://github.com/user-attachments/assets/8425bc2e-c89e-4419-b96b-878dacd67cb6)
![CoLabs Add a project](https://github.com/user-attachments/assets/84445947-580e-488c-886a-6105c843cdc0)
