### ISSUE TITLE
Feature: Develop the footer 

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#2]
## Description
Develop the footer as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8?node-id=4-598).

## Tasks
- [ ] Develop the footer as per the Figma designs
- [ ] Make sure the components are fully responsive
- [ ] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![Screenshot_20241030-140752](https://github.com/user-attachments/assets/285608c9-1083-4d5a-8eef-895de0204d54)

**Comment by DoHuyThinh** [comment]
Can you assign this to me, pls?

**Comment by DoHuyThinh** [comment]
I tried to make one like your illustration.
![Screenshot 2024-11-02 153311](https://github.com/user-attachments/assets/f41730f9-0317-440c-8745-4a9e3f341e78)
