### ISSUE TITLE
Feature: Develop the sidebar

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#20]
## Description
Develop the sidebaras per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=11544-8713&node-type=frame&t=QP5ajT4tDzJ46YUn-0). 
 

## Tasks
- [x] Develop sidebar as per the Figma designs
- [x] Make sure the components are fully responsive
- [x] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality
- [x] Include a list of any API endpoints required in the pull request description, if applicable

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![CoLabs Sidebar](https://github.com/user-attachments/assets/74a7ec76-cba2-4f4e-8a74-903b72119a66)

**Comment by crunchydosa123** [comment]
Hi, is this assigned? I can help

**Comment by tigawanna** [comment]
anyone can take it on
