### ISSUE TITLE
Feature: Develop the activities section

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#22]
## Description
Develop the activities section per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=11544-8713&node-type=frame&t=QP5ajT4tDzJ46YUn-0). 
 

## Tasks
- [ ] Develop the activities section as per the Figma designs
- [ ] Make sure the components are fully responsive
- [ ] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality
- [ ] Include a list of any API endpoints required in the pull request description, if applicable

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![CoLabs Activities](https://github.com/user-attachments/assets/b88ed5d0-8f44-4048-8a60-42f37f62f135)

**Comment by Blackie360** [comment]
@ayuboketch  are you still working on this one?

**Comment by ayuboketch** [comment]
Yes i am
