### ISSUE TITLE
Feature: Develop the challenges and contributors section

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#23]
## Description
Develop the challenges and contributors section per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8/SpaceYaTech-Website-Re-design?node-id=11544-8713&node-type=frame&t=QP5ajT4tDzJ46YUn-0). 
 

## Tasks
- [ ] Develop the challenges and contributors section as per the Figma designs
- [ ] Make sure the components are fully responsive
- [ ] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality
- [ ] Include a list of any API endpoints required in the pull request description, if applicable

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![CoLabs Challenges](https://github.com/user-attachments/assets/1728fbb7-8941-4045-9e00-d871c99a35d7)

**Comment by serenebabu2022** [comment]
Hi, Can I work on this
