### ISSUE TITLE
Feature: Develop hero section 

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#3]
## Description
Develop the CoLabs page hero section as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8?node-id=4-598).

## Tasks
- [ ] Develop the hero section as per the Figma designs
- [ ] Make sure the components are fully responsive
- [ ] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![Screenshot_20241030-140551](https://github.com/user-attachments/assets/0a1a69fe-2a68-41bb-9150-1c5494924897)

**Comment by SusanGithaigaN** [comment]
@bridgitkanini can you assign me this issue?
