### ISSUE TITLE
Feature: Develop add a project page 

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#4]
## Description
Develop the add project page as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8?node-id=4-598).

## Tasks
- [x] Develop the add project page as per the Figma designs
- [x] Make sure the components are fully responsive
- [x] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![Screenshot_20241030-140623](https://github.com/user-attachments/assets/25dfc2a2-6ef2-479a-b7c1-d50724dbab48)

**Comment by droffilc1** [comment]
@bridgitkanini I would like to work on this
