### ISSUE TITLE
Feature: Develop search and filter section

### ISSUE THREAD

**Issue by bridgitkanini** [SpaceyaTech/CoLabs-Frontend#5]
## Description
Develop the the search and filter section, including the filter projects modal, as per the [Figma designs](https://www.figma.com/design/2r8LJbRj7TEXZ7obQvVeb8?node-id=4-598).

## Tasks
- [ ] Develop the feature as per the Figma designs
- [ ] Make sure the components are fully responsive
- [ ] Write _Unit_ and _e2e_ tests in the `tests` folder, to test the components' look, feel, and functionality

## Tools to use for tests:
-  **Vitest** for Unit tests
-  **Playwright** for e2e tests

![1730288797152](https://github.com/user-attachments/assets/80c02800-dc80-4828-9403-43cd892916dd)

![Screenshot_20241030-140702](https://github.com/user-attachments/assets/ec6ac16b-d1e0-49cb-8096-71ab9227b4b8)

**Comment by DoHuyThinh** [comment]
Can I try it?
